apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
  - namespace.yaml
  - elasticsearch-deployment.yaml
  - logstash-deployment.yaml
  - kibana-deployment.yaml
  - filebeat-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: askyia
  app.kubernetes.io/managed-by: kustomize
  environment: production