apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
  - namespace.yaml
  - elasticsearch.yaml
  - logstash.yaml
  - kibana.yaml
  - filebeat.yaml

commonLabels:
  app.kubernetes.io/part-of: askyia
  app.kubernetes.io/managed-by: kustomize