apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "askyia.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "askyia.labels" . | nindent 4 }}
data:
  API_V1_STR: {{ .Values.backend.env.API_V1_STR | quote }}
  PROJECT_NAME: {{ .Values.backend.env.PROJECT_NAME | quote }}
  LOG_LEVEL: {{ .Values.backend.env.LOG_LEVEL | quote }}
  LOG_FORMAT: {{ .Values.backend.env.LOG_FORMAT | quote }}
  CHROMADB_HOST: "chromadb"
  CHROMADB_PORT: {{ .Values.chromadb.service.port | quote }}
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: {{ .Values.postgres.service.port | quote }}
  POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}