apiVersion: v1
kind: Secret
metadata:
  name: {{ include "askyia.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "askyia.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
  DATABASE_URL: {{ include "askyia.databaseUrl" . | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  JWT_ALGORITHM: {{ .Values.secrets.jwtAlgorithm | quote }}
  ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.secrets.accessTokenExpireMinutes | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | quote }}
  SERPAPI_API_KEY: {{ .Values.secrets.serpapiApiKey | quote }}
  BRAVE_API_KEY: {{ .Values.secrets.braveApiKey | quote }}