apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: askyia

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres-deployment.yaml
  - chromadb-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: askyia
  app.kubernetes.io/managed-by: kustomize