apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - prometheus/config.yaml
  - prometheus/rules.yaml
  - prometheus/deployment.yaml
  - grafana/config.yaml
  - grafana/dashboards/askyia-overview.json
  - grafana/deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: askyia
  app.kubernetes.io/managed-by: kustomize